/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2016 Tellerva, Marc Lawrence
 *
 * Permission is hereby granted, free of charge, to any
 * person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the
 * Software without restriction, including without
 * limitation the rights to use, copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software
 * is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice
 * shall be included in all copies or substantial portions
 * of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
 * KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
 * THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

package me.scarlet.undertailor.resource;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.utils.Disposable;

/**
 * Factory and data bag for an underlying {@link Disposable}
 * resource.
 * 
 * <p>This class works together with a {@link Resource}
 * class in order to allow the underlying Disposable to be
 * removed from memory when found to no longer be in use.
 * Implementations of this class should only implement the
 * three abstract methods to generate the Disposable and
 * Resource associated with itself, as well as be a data bag
 * for any data meant to be consistent across instances of
 * the Disposable.</p>
 *
 * @param <V> the produced underlying Disposable
 * @param <T> the produced Resource holding and interacting
 *        with the Disposable
 */
public abstract class ResourceFactory<V extends Disposable, T extends Resource<V>> {

    V disposable;
    ResourceReference<V, T> reference;
    
    /**
     * Generates a new {@link Disposable} of the type
     * assigned to this {@link ResourceFactory}.
     * 
     * @return a new Disposable
     */
    protected abstract V newDisposable();
    
    /**
     * Generates a new {@link Resource} of the type
     * assigned to this {@link ResourceFactory}.
     * 
     * @return a new Disposable
     */
    protected abstract T newResource();
    
    /**
     * Checks whether or not the provided {@link Disposable}
     * instance can be removed from memory.
     * 
     * <p>While this method will be used primarily for the
     * {@link ResourceHandler} to query whether or not the
     * current Disposable reference held by the factory can
     * be safely disposed, this method will also be
     * referenced for any loose Disposables that were
     * deferred and belonged to this factory.</p>
     * 
     * @param disposable the Disposable to check
     * 
     * @return whether or not it can be disposed without
     *         error or unintended behavior
     */
    public abstract boolean isDisposable(V disposable);
    
    /**
     * Queries whether or not the {@link Disposable}s
     * generated by this {@link ResourceFactory} should be
     * disposed on the LWJGL Application thread (through
     * {@link Gdx.app#postRunnable()}).
     * 
     * @return whether or not this ResourceFactory's
     *         resources should be disposed on the game's
     *         main thread
     */
    protected boolean disposeOnGameThread() { return false; }
    
    /**
     * Called right before the underlying {@link Resource}
     * and {@link Disposable} are dispoed through calling
     * {@link #dispose()}.
     */
    protected void onDispose() {}
    
    /**
     * Returns the current instance of the
     * {@link Disposable} held by this
     * {@link ResourceFactory}, of which may be null.
     * 
     * @return the current Disposable, or null if it was
     *         previously disposed and not regenerated, or
     *         never generated prior
     */
    protected final V getDisposable() {
        return this.disposable;
    }
    
    /**
     * Returns the current instance of the {@link Resource}
     * held by this {@link ResourceFactory}.
     * 
     * <p>If the current Resource has yet to exist, a new
     * one will be generated and stored by the factory until
     * its {@link #dispose()} method has been called. The
     * disposable is generated first, followed by the
     * resource.</p>
     * 
     * @return the current Resource instance
     */
    public final T getResource() {
        boolean removeFromDeferrence = true;
        if(this.disposable == null) {
            this.disposable = this.newDisposable();
            removeFromDeferrence = false;
        }
        
        if(this.reference == null || this.reference.get() == null) {
            T resource = this.newResource();
            resource.disposable = this.disposable;
            this.reference = new ResourceReference<>(resource, ResourceHandler.QUEUE, this);
            if(removeFromDeferrence) ResourceHandler.removeFromDeferrence(this.disposable);
        }
        
        return this.reference.get();
    }
    
    /**
     * Disposes of the underlying {@link Resource} and
     * {@link Disposable} pair held by this
     * {@link ResourceFactory}.
     */
    public final void dispose() {
        this.onDispose();
        if(this.disposable != null) {
            if(this.disposeOnGameThread()) {
                Disposable copy = this.disposable;
                Gdx.app.postRunnable(() -> copy.dispose());
            } else {
                this.disposable.dispose();
            }
            
            this.disposable = null;
        }
        
        if(this.reference != null) {
            if(this.reference.get() != null) this.reference.get().disposable = null;
            this.reference.enqueue();
            this.reference = null;
        }
    }
}
