language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
    
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
  
  
notifications:
  email: false

install: ""
  
script: 
  - "chmod +x gradlew"
  - "./gradlew desktop:dist"
